apiVersion: etcd.oschina.cn/v1alpha1
kind: EtcdBackup
metadata:
  name: etcdbackup-sample
spec:
  endpoints: "localhost:2379"  # 备份的节点 etcd 地址
  storageType: s3  # 指定备份类型
  backupImage: busybox:latest
  s3:
    path: "foo-bucket/snapshot.db"  # 数据存放目录
    s3Secret: "secret"   # 包含 accessKeyID 与 secretAccessKey
  oss:
    path: "foo-bucket/snapshot.db"
    ossSecret: "secret"